# Generated by Django 4.1.3 on 2023-06-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role')),
            ],
        ),
    ]
