# Generated by Django 4.1.3 on 2023-06-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='roles.role'),
        ),
    ]
