# Generated by Django 4.1.3 on 2023-06-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
