# Generated by Django 4.1.3 on 2023-06-20 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_remove_patient_role_patient_email'),
        ('services', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('end', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('1', 'Agendado'), ('2', 'Atentido'), ('3', 'Não Atendido'), ('4', 'Cancelado'), ('5', 'Faltou'), ('6', 'Remarcar')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.professional')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
