# Generated by Django 4.1.3 on 2023-06-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_end_alter_booking_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.BigIntegerField(),
        ),
    ]
